resources:
    App\Entity\Product:
        description: 'An product from my shop'
        attributes:
            pagination_items_per_page: 20
    App\Entity\Offer:
        description: 'An offer from my shop'
        iri: 'http://schema.org/Offer'
        attributes:
            pagination_items_per_page: 20
        collectionOperations:
            get: ~
        itemOperations:
            get: ~